# Generated by Django 3.1.2 on 2021-08-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesModel',
            new_name='Article',
        ),
    ]
