# Generated by Django 3.1.2 on 2021-08-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20210820_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
