# Generated by Django 3.1.2 on 2021-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20210820_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
