# Generated by Django 3.1.2 on 2021-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20210820_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
