# Generated by Django 3.1.2 on 2021-08-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20210820_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
